package com.andrewxa.greendaoretrofit.bd;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.andrewxa.greendaoretrofit.bd.NewsItem;

import com.andrewxa.greendaoretrofit.bd.NewsItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsItemDaoConfig;

    private final NewsItemDao newsItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsItemDaoConfig = daoConfigMap.get(NewsItemDao.class).clone();
        newsItemDaoConfig.initIdentityScope(type);

        newsItemDao = new NewsItemDao(newsItemDaoConfig, this);

        registerDao(NewsItem.class, newsItemDao);
    }
    
    public void clear() {
        newsItemDaoConfig.clearIdentityScope();
    }

    public NewsItemDao getNewsItemDao() {
        return newsItemDao;
    }

}
